config/routes.rb
Rails.application.routes.draw do
  root :to => "gambars#index"
  resources :gambars

end

app/models/gambar.rb
class Gambar < ActiveRecord::Base
  validates :title, presence: true

  has_attached_file :nama_gambar, :styles => {:medium => "400x200>", :thumb => "200x100>", :default_url => ""}
  validates_attachment_content_type :nama_gambar, :content_type => /\Aimage\/.*\Z/
  validates_attachment_size :nama_gambar, :less_than => 200.kilobytes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gambars_controller.rb
class GambarsController < ApplicationController
  def index
    @gambars = Gambar.all
  end
  
  def create
    @gambar = Gambar.new(params_photo)
    if @gambar.save
      redirect_to gambars_path, :notice => "Upload Image #{@gambar.title} Success!"
    else
      render "new", :error => "Upload Image #{@gambar.title} Failed!"
    end
  end

  def new
    @gambar = Gambar.new
  end

  def edit
    @gambar = Gambar.find(params[:id])
  end
  
  def update
     @gambar = Gambar.find(params[:id])
    if @gambar.update(params_photo)
      redirect_to gambars_path, :notice => "Update Image #{@gambar.title} Success"
    else
      render "new", :error => "Update Image #{@gambar.title} Failed"
    end
  end
  
  def show
    @gambar = Gambar.find(params[:id])
  end

  def destroy
    @gambar = Gambar.find(params[:id])
    if @gambar.destroy
      redirect_to gambars_path, :notice => "Delete Image #{@gambar.title} Success"
    else
      redirect_to gambars_path, :error => "Delete Image #{@gambar.title} Failed"
    end
  end

  private
    def params_photo
      params.require(:gambar).permit(:title, :nama_gambar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gambars/_form.html.erb
<% if @gambar.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @gambar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @gambar do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :nama_gambar %>
    <%= f.file_field :nama_gambar, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/gambars/edit.html.erb
<h1>Edit Photo</h1>
<b>Picture now</b><br>
<%= image_tag @gambar.nama_gambar.url(:medium) %>
<%= render "form" %>

app/views/gambars/index.html.erb
<h1>Welcome</h1>
<link href = "aplication.css" rel = "stylesheet" type = "text/css"/>
<div class="row">
  <% @gambars.each do |gambar| %>
    <div class="col-lg-3">
      <%= link_to (image_tag gambar.nama_gambar.url(:thumb)), gambar_path(gambar) %><br>
      <b><%= gambar.title %></b><br>
      <%= link_to "Edit", edit_gambar_path(gambar), :class =>"link1" %> |
      <%= link_to "Delete", gambar_path(gambar), :class =>"link1" ,:method => :delete, :data => {confirm: "Are you sure want to delete this file?"} %>
    </div>
  <% end %>
</div>

app/views/gambars/new.html.erb
<h1>Add new Image</h1>
<%= render "form" %>

app/views/gambars/show.html.erb
<h2><%= @gambar.title %></h2>
<%= link_to (image_tag @gambar.nama_gambar.url(:medium)), gambar_path(@gambar) %><br>
<%= link_to "Edit", edit_gambar_path(@gambar) %> |
<%= link_to "Delete", gambar_path(@gambar), :method => :delete, :data => {confirm: "Are you sure want to delete this file?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tugas3</title>
  <link href = "aplication.css" rel="stylesheet" type="text/css"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style = "font-family:Arial;">
<nav class = "navbar" role="navigation" style = "background-color:#66C2C2;">
	<div class = "container">
		<div class = "navbar-header">
			<!--<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"/>
				<span class="icon-bar"/>
				<span class="icon-bar"/>
			</button>-->
			<ul>
				<li style = "display:inline;"><%= link_to "Gallery", gambars_path, :class => "navbar-brand" %></li>
			
				<li style = "display:inline;padding:20px;"><%= link_to "Add Image", new_gambar_path, :class => "navbar-brand" %></li>
			</ul>
		</div>
		
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			
		</div>
	</div>	
</nav>

<div class="container">
    <div class="row">
      <div class="col-lg-12">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>